# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5f89bb5b2fc1745a4e41d09f6d1abbd4"
name = "nutrtition"
application_url = "https://project-kx8dj.vercel.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_proxy]
url = "https://project-kx8dj.vercel.app/api/proxy"
prefix = "apps"
subpath = "nutrition-coach"

[webhooks]
api_version = "2025-10"
